name: Remote Download to Artifacts

on:
  workflow_dispatch: # 允许手动点击运行

jobs:
  download_job:
    runs-on: ubuntu-latest
    steps:
    - name: Download File
      run: |
        # 创建临时目录并下载文件
        mkdir -p my_files
        cd my_files
        wget "https://models.datalab.to/layout/2025_09_23/model.safetensors"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-safetensors-file  # 下载时的压缩包名称
        path: my_files/model.safetensors  # 要保存的文件路径
        retention-days: 5  # 可选：设置保留天数（默认90天，这里设为5天足够你下载了）
