name: Remote Download to Release

on:
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Large File
      run: |
        # 创建一个文件夹存放文件
        mkdir -p downloads
        cd downloads
        # 使用 wget 下载你的目标文件，-O 后面是保存的文件名
        wget "https://models.datalab.to/layout/2025_09_23/model.safetensors" -O model.safetensors

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        files: downloads/model.safetensors
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
